### ISSUE TITLE
Segfault on start

### ISSUE THREAD

**Issue by logenkain** [mrshampoo/jeti-filemanager#2]
Tried to use it in void, here is your log.
Tried in terminology and xterm.  Tried with bash, sh, and fish.  Run under Enlightenment.

try to locate configfiles ERROR: there are no config files!! ERROR: get_terminalname: no config -> fallback terminal set to xterm   trying to initiate fileActions...
  fileAction initiated
  trying to initiate soundeffects...
 WARNING: soundeffects: config not read

**Comment by mrshampoo** [comment]
tanks mate, I just got home from my irl-jobb.
i will start fixing this right away :)

**Comment by mrshampoo** [comment]
Details: 
this bug apperad when i uncomented stuff under "remove unused mallocation" in file: environment.c, function: init_soundeffects and init_shortcuts, right before return;

why did i:
it was first put there to remove the last unused mallocation. and was later commented out because this issue in a earlier version.
it was later uncommented again when i tried to make more clean code, and wonderd why i had commented  it out. since i use this program myself on daily bases  i have my own rc files and use XGD-directorys so jeti always find a useful rc somewhere. there for i didn't notes anything and let the lines continue to be uncommented.

when will this bugg be fully fixed:
the bug is fixed, but i want to control check if i can make this nicer, before i upload.
i will also see if i can fix another small bug that i just remembered.
irl also reminds itself to day (Landry day)
but a new version will be uploaded before the night has fallen over Europe ;)

**Comment by mrshampoo** [comment]
updated, there is now 1.1.3 available ;)

**Comment by mrshampoo** [comment]
and now there also is a new template waiting 
https://github.com/voidlinux/void-packages/pull/4042

**Comment by mrshampoo** [comment]
i will close this issue in 24 hours, if no objections.
considering this as solved :)

**Comment by logenkain** [comment]
Seems to work!

Now I just need to learn how to use it ><
